openapi: 3.0.1
info:
  title: Cinema room managment API
  description: TD2 STD21011
  version: 1.0.0
servers:
  - url: https://ciné.STD21011.com
tags:
  - name: Rooms
  - name: Movies
  - name: Projections
paths:
  /rooms:
    get:
      tags:
        - "Rooms"
      summary: Get all Rooms
      operationId: getRooms
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Room"
        400:
          description: Error
          content: {}
  /rooms/{id}:
    get:
      tags:
        - "Rooms"
      summary: get the room by specified id
      operationId: getRoom
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Room"
  /Movies:
    get:
      tags:
        - "Movies"
      summary: Get all Movies
      operationId: getMovies
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Movie"
        400:
          description: Error
          content: {}
    put:
      tags:
        - "Movies"
      summary: modifies entirely a Movie list
      requestBody:
        description: new Movie
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/NewMovie"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Movie"
        400:
          description: Error
          content: {}

  /Movies/{id}:
    get:
      tags:
        - "Movies"
      summary: get the Movie by specified id
      operationId: getMovie
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Movie"
        400:
          description: Error
          content: {}
    put:
      tags:
        - "Movies"
      summary: allows you to modify Movie data except its id
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
      requestBody:
        description: new Movie
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewMovie"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Movie"
        400:
          description: Error
          content: {}
    delete:
      tags:
        - "Movies"
      summary: deletes a Movie by referring to its id
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
      responses:
        200:
          description: Success
          content:
            text/plain:
              schema:
                type: string
                example: "Returns the id of the deleted student"

        400:
          description: Error
          content: {}
  /Movies/category:
    get:
      tags:
        - Movies
      summary: Select Movies by category
      parameters:
        - name: category
          in: query
          required: true
          schema:
            type: string
          examples:
            changeMovie:
              summary: Change categories
              value:
                Moviecategorie: drame
      responses:
        200:
          description: List of Movies
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Movie"
        400:
          description: Bad request
          content: {}

  /projections:
    get:
      tags:
        - "Projections"
      summary: Get all projections
      operationId: getProjections
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Projection"
        400:
          description: Error
          content: {}
    put:
      tags:
        - "Projections"
      summary: modifies entirely a Projection list
      requestBody:
        description: new Movie
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: integer
                allOf:
                  - $ref: "#/components/schemas/NewProjection"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Projection"
        400:
          description: Error
          content: {}
    post:
      tags:
        - "Projections"
      summary: creates a new Projection
      requestBody:
        required: true
        description: new Movie
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewProjection"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Projection"
        400:
          description: Error
          content: {}
    patch:
      tags:
        - "Projections"
      summary: patch
      description: |
        Possible changes on:
        * Movie: change
        * room: change
        * hour: change hour
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/Projection"
            examples:
              changeMovie:
                summary: Change some Movies
                value:
                  - id: 1
                    MovieId: 1
                  - id: 2
                    MovieId: 2
              changeRoom:
                summary: Change room
                value:
                  - id: 1
                    roomId: B
                  - id: 2
                    roomId: B
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Projection"
  /projections/{id}:
    get:
      tags:
        - "Projections"
      summary: get the projection by specified id
      operationId: getProjection
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Projection"
        400:
          description: Error
          content: {}
    put:
      tags:
        - "Projections"
      summary: allows you to modify projection data except its id
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
      requestBody:
        required: true
        description: new projection
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
              allOf:
                - $ref: "#/components/schemas/NewProjection"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Projection"
        400:
          description: Error
          content: {}
    delete:
      tags:
        - "Projections"
      summary: deletes a projection by referring to its id
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
      responses:
        200:
          description: Success
          content:
            text/plain:
              schema:
                type: string
                example: "Returns the id of the deleted projection"

        400:
          description: Error
          content: {}
  /projections/category:
    get:
      tags:
        - Projections
      summary: Select Movies diffusion by category
      parameters:
        - name: category
          in: query
          required: true
          schema:
            type: string
      responses:
        200:
          description: List of Movies
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Categories"
        400:
          description: Bad request
          content: {}
  /Projections/WeekDate:
    get:
      tags:
        - Projections
      summary: Lists of projections in a week by date
      operationId: calendar
      parameters:
        - name: WeekDate
          in: query
          required: true
          schema:
            type: string
          examples:
            changeMovie:
              summary: WeekDate
              value:
                Date: "2022-08-01"
      responses:
        200:
          description: List of Movies
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/WeekProjections"
        400:
          description: Bad request
          content: {}
          
components:
  schemas:
    Room:
      type: object
      properties:
        id:
          type: string
          example: "A"
        capacity:
          type: number
          example: 30

    NewMovie:
      type: object
      properties:
        title:
          type: string
          example: "Thor Love and thunder"
        duration:
          type: string
          example: 2h
        summary:
          type: string
          example: Le roi d'Argard
        director:
          type: string
          example: Marvel studios
        date:
          type: string
          format: date
    Movie:
      type: object
      properties:
        id:
          type: number
      allOf:
        - $ref: "#/components/schemas/NewMovie"
    NewProjection:
      type: object
      properties:
        MovieId:
          type: integer
          example: 1
        roomId:
          type: string
          default: A
          enum:
            - A
            - B
        diffusion:
          type: string
          example: "2022-08-01 19:30"
    Projection:
      type: object
      properties:
        id:
          type: number
          example: "1"
        diffusion:
          type: string
          example: "2022-08-01 19:30"
        Movie:
          $ref: "#/components/schemas/Movie"
        room:
          $ref: "#/components/schemas/Room"
    WeekProjections:
      oneOf: 
        -  $ref: "#/components/schemas/Projection"
        -  $ref: "#/components/schemas/Projection"
        -  $ref: "#/components/schemas/Projection"
    NewCategories:
      type: object
      properties:
        type:
          type: string
          example: drame
    Categories:
      allOf:
        - $ref: "#/components/schemas/NewCategories"
      type: object
      properties:
        id:
          type: integer
